# Generated by Django 5.2.16 on 2026-07-23 03:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Hata'), ('request', 'İstek'), ('complaint', 'Şikayet'), ('question', 'Soru')], default='question', max_length=16)),
                ('subject', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('open', 'Açık'), ('in_progress', 'İnceleniyor'), ('answered', 'Yanıtlandı'), ('closed', 'Kapatıldı')], default='open', max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('os_version', models.CharField(blank=True, max_length=32)),
                ('device_model', models.CharField(blank=True, max_length=48)),
                ('locale', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('user', 'Kullanıcı'), ('staff', 'Ekip')], max_length=8)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='feedback.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-updated_at'], name='feedback_ti_status_87dadd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', '-created_at'], name='feedback_ti_user_id_afbff2_idx'),
        ),
    ]
