# Generated by Django 5.2.16 on 2026-07-27 21:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64)),
                ('message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to='feedback.ticket')),
            ],
            options={
                'indexes': [models.Index(fields=['chat_id', 'message_id'], name='feedback_te_chat_id_c38d78_idx')],
                'constraints': [models.UniqueConstraint(fields=('chat_id', 'message_id'), name='uniq_telegram_chat_message')],
            },
        ),
    ]
